### PR TITLE
Update get-quicksnap.sh

### PR DESCRIPTION
**Pull request by shipcod3**
updating the new location of the file and the filename

### CODE REVIEW

**Comment by attackvector** [comment]
thanks for this @shipcod3 !

**Comment by shipcod3** [comment]
Your welcome @attackvector :)

**Comment by kaneda** [comment]
@shipcod3 the host project is https://github.com/kaneda/knife for future reference, AVL is not actively maintained. Do you have a hosted md5sum as well, while I'm updating this?

**Comment by shipcod3** [comment]
Nope I don't have one :)

**Comment by kaneda** [comment]
@shipcod3 OK, how about instead, can you version the file, so that it's quicksnap_1.0.py or something, then I'll checksum it and compare against a static md5?

**Comment by shipcod3** [comment]
I told my friend to update it, this is the new location: https://www.soldierx.com/system/files/sxlabs/projects/alcohologist/quicksnap.tar_0.gz

**Comment by kaneda** [comment]
@shipcod3 ty, i'll post the update to knife in a bit, working on a larger one now anyways

**Comment by shipcod3** [comment]
Okay got it! Thanks for the time @kaneda 

You are doing a good job. Please keep up the good work.

**Comment by kaneda** [comment]
@shipcod3 ty, you can find the PR with your changes (and others) here https://github.com/kaneda/knife/pull/4

**Comment by shipcod3** [comment]
Yep, looks good :+1:

**Comment by thomhastings** [comment]
@shipcod3 you rule!

**Comment by shipcod3** [comment]
your welcome @thomhastings and thanks for the quick update :)

**Comment by thomhastings** [comment]
I try to be responsive -_-

**Comment by attackvector** [comment]
@thomhastings @ksoona @kaneda @shipcod3 @shyamsalimkumar don't we all?

**Comment by shipcod3** [comment]
@attackvector :+1:

**Pull request closed without merging**
